FROM ghcr.io/osgeo/gdal:ubuntu-small-latest-amd64

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git

RUN apt-get update && apt-get install -y python3-pip
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade wheel

# to make opencv work
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY requirements_sig.txt /tmp/requirements.txt
WORKDIR /tmp
RUN pip install --no-cache-dir -r requirements.txt